### ISSUE TITLE
Precision for /etc/network/interfaces

### ISSUE THREAD

**Issue by Pololot64** [Code-Exec/Proxmox_NAT_Patch#1]
This is not an issue per se, but a request for clarification in readme.md / 3

Should /etc/network/interfaces look like this?

-----------------------------------------------------------------------------------------

auto vmbr0
#private sub network
iface vmbr0 inet static
        address  10.10.10.1
        netmask  255.255.255.0
        bridge-ports none
        bridge-stp off
        bridge-fd 0

        post-up   echo 1 > /proc/sys/net/ipv4/ip_forward
        post-up   iptables -t nat -A POSTROUTING -s '10.10.10.0/24' -o eno1 -j MASQUERADE
        post-down iptables -t nat -D POSTROUTING -s '10.10.10.0/24' -o eno1 -j MASQUERADE

auto vmbr1
#private sub network
iface vmbr1 inet static
address  10.10.10.1
netmask  255.255.255.0
bridge-ports none
bridge-stp off
bridge-fd 1

post-up   echo 1 > /proc/sys/net/ipv4/ip_forward
post-up   iptables -t raw -I PREROUTING -i fwbr+ -j CT --zone 1
post-down iptables -t raw -D PREROUTING -i fwbr+ -j CT --zone 1

-----------------------------------------------------------------------------------------

Thank you for the great work

**Comment by Code-Exec** [comment]
You have two identical IP addr on two interfaces (vmbr0 & vmbr1) in your sample. Its impossible...

**Comment by Pololot64** [comment]
My server gets a reserve IP address from host network via "DHCP Static allocation"  based on its Mac address.

Here are the default settings of the server. 

How could this work with your setup? I am not a network expert. 

---------------------------------------------------

# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
allow-hotplug eth0
iface eth0 inet dhcp
iface eth0 inet6 static
address XXXX:YYYY:ZZZZ:XXXX:YYYY:ZZZZ:XXXX:YYYY
netmask 64
post-up ip -6 route add fe80::1 dev eth0
post-up ip -6 route add default via fe80::1 dev eth0
post-down ip -6 route del default via fe80::1 dev eth0
post-down ip -6 route del fe80::1 dev eth0

--------------------------------------------------- 

Thanks a lot for your help.

**Comment by Code-Exec** [comment]
You must have two interfaceses - one outside (internet) and one inside (virtual local). I do not saw second interface in yor file. You may create new virtual interface from Proxmox GUI
