### ISSUE TITLE
error on proxmox 7.4.3

### ISSUE THREAD

**Issue by DevataDev** [Code-Exec/Proxmox_NAT_Patch#7]
Hi Thanks for your hardwork,
i tried on pve 7.4.3 but its error: 
BEGIN failed--compilation aborted at /usr/bin/pveproxy line 11, <DATA> line 960.

Do you have any idea on this ? 

Thanks

**Comment by Code-Exec** [comment]
Hello. I think it may be related with that PVE finally update firewall file and patch didn't work. Any way thanks for you feedback, I will try to fix it or write you so fast as I can.

**Comment by Code-Exec** [comment]
Hello. Glad to say, that new patcher version was implement. Old version way (universal script patcher) not worked as I want. Pay attention, that now need to download release (packed script and diffs base). If you still have a questions or need a help - welcome. Thanks for your patient.
